#bigipdevicefacts.yaml
#Doesn't work before version 2.7.
#This playbook gets information about a BigIP
---

- name: Show information about a BigIP
  hosts: sandbox
  connection: local
  pre_tasks:
  vars_files:
   - creds.yaml

  tasks:

   - name: Collect BIG-IP facts
     register: output
     bigip_device_facts:
       gather_subset:
         - interfaces
         - vlans
       validate_certs: no
       server: "{{ inventory_hostname }}"
       password: "{{ password }}"
       user: "{{ user }}"
     delegate_to: localhost

   - debug: msg="{{ output.stdout }}"
