#This playbook creates a pool with nodes, a SNAT
#pool, and a VIP
---
 
- hosts: all
  pre_tasks:
    - include_vars: creds.yaml
   
  tasks:
   - name: Create a pool
     bigip_pool:
         lb_method: round_robin
         name: web1
         slow_ramp_time: 120
         validate_certs: no
         monitor_type: m_of_n
         monitors:
           - http
         server: "{{ inventory_hostname }}"
         password: "{{ password }}"
         user: "{{ user }}"
     delegate_to: localhost
