#This playbook creates a pool
---

- name: Create a pool
  hosts: all
  pre_tasks:
  vars_files:
   - creds.yaml

  tasks:

   - name: Display all variables/facts known for a host
     debug:
       msg: "User is {{ user }}"
       
   - name: Create a pool
     bigip_pool:
         lb_method: round-robin
         name: web3
         slow_ramp_time: 120
         validate_certs: no
         monitor_type: single
         monitors:
           - http
         server: "{{ inventory_hostname }}"
         password: "{{ password }}"
         user: "{{ user }}"
     delegate_to: localhost
