---

- name: Create a VIP, pool, pool members and nodes
  hosts: bigip2  connection: local

  vars:
    provider:
      password: "{{ f5_password }}"
      server: "{{ ansible_host }}"
      user: "{{ f5_username }}"
      validate_certs: "{{ validate_certs }}"
      server_port: "{{ f5_server_port }}"

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      with_items:
        - host: 192.168.202.253
          name: centos1
        - host: 192.168.202.254
          name: centos2
      delegate_to: localhost

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: ansible-created-vip
        destination: 192.168.200.250
        name: ansiblevip
        pool: web
        port: 80
        snat: Automap
        profiles:
          - http
          - clientssl
      delegate_to: localhost
